name: Deploy HUGO to Firebase
on:
  push:
    branches: [ main ]
jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Change to AI Exchange Directory
      run: |
        cp -r content/ai_exchange/* .
    - uses: wajahatkarim3/Hugo-On-Fire@master
      with:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
