on:
  push:
    branches:
      - main
name: Deploy HUGO to the Firebase
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Change to AI Exchange Directory
      run: |
        cd /content/ai_exchange
    - uses: vudoodv/deploy-hugo-to-the-firebase@master
      with:
        firebase-token: ${{ secrets.firebase_token }}